// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package schema

// Defines values for ErrorType.
const (
	ErrorTypeForbidden           ErrorType = "http://secapi.cloud/errors/forbidden"
	ErrorTypeInternalServerError ErrorType = "http://secapi.cloud/errors/internal-server-error"
	ErrorTypeInvalidRequest      ErrorType = "http://secapi.cloud/errors/invalid-request"
	ErrorTypePreconditionFailed  ErrorType = "http://secapi.cloud/errors/precondition-failed"
	ErrorTypeResourceConflict    ErrorType = "http://secapi.cloud/errors/resource-conflict"
	ErrorTypeResourceNotFound    ErrorType = "http://secapi.cloud/errors/resource-not-found"
	ErrorTypeUnauthorized        ErrorType = "http://secapi.cloud/errors/unauthorized"
	ErrorTypeValidationError     ErrorType = "http://secapi.cloud/errors/validation-error"
)

// Error A detailed error response see https://datatracker.ietf.org/doc/html/rfc7807.
type Error struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	Instance string `json:"instance"`

	// Meta A meta object containing non-standard meta-information about the error.
	Meta    *map[string]interface{} `json:"meta,omitempty"`
	Sources []ErrorSource           `json:"sources"`

	// Status The HTTP status type ([http://secapi.cloud/errors/-rfc7231], Section 6)
	// generated by the origin server for this occurrence of the problem.
	Status float32 `json:"status"`

	// Title A short, human-readable summary of the problem
	// type.  It SHOULD NOT change from occurrence to occurrence of the
	// problem, except for purposes of localization (e.g., using
	// proactive content negotiation; see [RFC7231], Section 3.4).
	Title string `json:"title"`

	// Type The type of error, expressed as a URI.
	Type string `json:"type"`
}

// Error400 A detailed error response see https://datatracker.ietf.org/doc/html/rfc7807.
type Error400 = Error

// Error401 A detailed error response see https://datatracker.ietf.org/doc/html/rfc7807.
type Error401 = Error

// Error403 A detailed error response see https://datatracker.ietf.org/doc/html/rfc7807.
type Error403 = Error

// Error404 A detailed error response see https://datatracker.ietf.org/doc/html/rfc7807.
type Error404 = Error

// Error409 A detailed error response see https://datatracker.ietf.org/doc/html/rfc7807.
type Error409 = Error

// Error412 A detailed error response see https://datatracker.ietf.org/doc/html/rfc7807.
type Error412 = Error

// Error422 A detailed error response see https://datatracker.ietf.org/doc/html/rfc7807.
type Error422 = Error

// Error500 A detailed error response see https://datatracker.ietf.org/doc/html/rfc7807.
type Error500 = Error

// ErrorSource An object containing references to the source of the error.
type ErrorSource struct {
	// Parameter A string indicating which URI query parameter caused the error.
	Parameter string `json:"parameter"`

	// Pointer A JSON Pointer [RFC6901] to the associated entity in the request document.
	Pointer string `json:"pointer"`
}

// ErrorType The type of error, expressed as a URI following RFC 7807 problem details.
// Each error type corresponds to a specific HTTP status code and error condition.
type ErrorType string
