filename: "zz_generated.{{.InterfaceName}}.go"
with-expecter: true
packages:
  github.com/eu-sovereign-cloud/go-sdk/pkg/regions.v1:
    config:
      all: true
      dir: mock/mockregions.v1
      outpkg: mockregions
  github.com/eu-sovereign-cloud/go-sdk/pkg/workspace.v1:
    config:
      all: true
      dir: mock/mockworkspace.v1
      outpkg: mockworkspace