filename: "zz_generated.{{.InterfaceName}}.go"
with-expecter: true
issue-845-fix: true
resolve-type-alias: false
packages:
  github.com/eu-sovereign-cloud/go-sdk/pkg/foundation.region.v1:
    config:
      all: true
      dir: mock/mockregion.v1
      outpkg: mockregion
  github.com/eu-sovereign-cloud/go-sdk/pkg/foundation.workspace.v1:
    config:
      all: true
      dir: mock/mockworkspace.v1
      outpkg: mockworkspace