filename: "zz_generated.{{.InterfaceName}}.go"
with-expecter: true
issue-845-fix: true
resolve-type-alias: false
packages:
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/extensions.activitylog.v1beta1:
    config:
      all: true
      dir: mock/spec/extensions.activitylog.v1beta1
      outpkg: mockactivitylog  
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/extensions.kubernetes.v1beta1:
    config:
      all: true
      dir: mock/spec/extensions.kubernetes.v1beta1
      outpkg: mockkubernetes  
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/extensions.loadbalancer.v1beta1:
    config:
      all: true
      dir: mock/spec/extensions.loadbalancer.v1beta1
      outpkg: mockloadbalancer  
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/extensions.natgateway.v1beta1:
    config:
      all: true
      dir: mock/spec/extensions.natgateway.v1beta1
      outpkg: mocknatgateway  
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/extensions.objectstorage.v1beta1:
    config:
      all: true
      dir: mock/spec/extensions.objectstorage.v1beta1
      outpkg: mockobjectstorage  
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/foundation.authorization.v1:
    config:
      all: true
      dir: mock/spec/foundation.authorization.v1
      outpkg: mockauthorization  
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/foundation.compute.v1:
    config:
      all: true
      dir: mock/spec/foundation.compute.v1
      outpkg: mockcompute  
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/foundation.network.v1:
    config:
      all: true
      dir: mock/spec/foundation.network.v1
      outpkg: mocknetwork
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/foundation.region.v1:
    config:
      all: true
      dir: mock/spec/foundation.region.v1
      outpkg: mockregion  
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/foundation.storage.v1:
    config:
      all: true
      dir: mock/spec/foundation.storage.v1
      outpkg: mockstorage  
  github.com/eu-sovereign-cloud/go-sdk/pkg/spec/foundation.workspace.v1:
    config:
      all: true
      dir: mock/spec/foundation.workspace.v1
      outpkg: mockworkspace
