on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "mock/**"
      - "hack/**"
      - "*.md"
  pull_request:

name: Tests

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache Go Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-go-1
      - name: Vet
        run: make vet
      - name: Run Formation
        run: make fmt
      - name: Check if all generated files are either not added or up to date in git
        run: if [[ -z $(git status --porcelain) ]]; then echo "ok"; else echo "Found modified files:"; git status --porcelain; exit 1; fi
      - name: Tests
        run: make test

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
      - name: Cache Go Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Lint
        run: make lint
